from pathlib import Path
from typing import Protocol


class AudioStorage(Protocol):
    def put(self, key: str, source: Path, content_type: str) -> None: ...
    def download(self, key: str, target: Path) -> None: ...
    def read(self, key: str) -> bytes: ...
    def delete(self, key: str) -> None: ...
